import { useState, useEffect, useCallback, useRef } from "react";
import { loadAll as fbLoad, saveAll as fbSave } from "./firebase.js";

const LOGO_SRC = "/logo.png";
const BANNER_SRC = "/banner.jpg";
const ADMIN_CODE = "aguia83000toulonjjb";

const C = {
  bg: "#080c14", bgAlt: "#0d1322", card: "#111827",
  red: "#9b1c1c", redLight: "#c53030", blue: "#1a2744", blueMid: "#1e3a5f", blueLight: "#2b5a8f",
  gold: "#d4952b",
  text: "#e8e6e1", textMuted: "#7a8599", border: "#1e293b", borderLight: "#2d3b52",
};

const DEFAULT_TEXTS = {
  heroTitle: "AGUIA JJB", heroSubtitle: "Jiu-Jitsu Brésilien à Toulon & La Moutonne",
  aboutTitle: "Qui sommes-nous",
  aboutText: "Aguia JJB est une association dédiée à la pratique et à la promotion du Jiu-Jitsu Brésilien. Fondée par des passionnés, notre mission est de transmettre les valeurs de cet art martial : discipline, respect, dépassement de soi et esprit de communauté. Nos entraînements sont encadrés par des instructeurs qualifiés dans une ambiance bienveillante. Au-delà du sport, Aguia JJB est un lieu de partage où chaque membre progresse à son rythme et s'épanouit dans un cadre motivant.",
  ctaTitle: "3 cours d'essai offerts !", ctaText: "Réservez votre place en nous contactant sur les réseaux ou via la rubrique contact.",
  offresTitle: "Rejoignez Aguia JJB",
  offresIntro: "Plongez dans l'univers du Jiu-Jitsu Brésilien ! Nos formules s'adaptent à tous : ados, adultes, débutants ou confirmés. Inscription simple et rapide via HelloAsso.",
  offresEssaiTitle: "Cours d'essai", offresEssaiText: "3 cours d'essai offerts pour découvrir le Jiu-Jitsu Brésilien dans notre club. Sans engagement. Contactez-nous pour réserver votre place.",
  offresAdhesionTitle: "Adhésion annuelle", offresAdhesionText: "Accès à tous les entraînements, dans tous les lieux, pour toute la saison sportive.",
  offresImportant: "L'inscription est valable pour l'année sportive, du 1er septembre au 31 août. Il n'est pas possible de décaler ou d'ajuster les dates d'inscription, y compris en cas d'absence prolongée.",
  lieuxTitle: "Lieux & Horaires", lieuxSubtitle: "Retrouvez tous nos créneaux d'entraînement sur la carte et dans le détail.",
  blogTitle: "Actualités", blogSubtitle: "Suivez l'actualité du club, résultats de compétitions, stages et événements.",
  palmaresTitle: "Palmarès", palmaresIntro: "Découvrez les résultats et accomplissements de nos athlètes.",
  legalTitle: "Mentions Légales",
  legalContent: "Association Aguia JJB\nAssociation loi 1901\nSiège social : Toulon, France\n\nDirecteur de la publication : Le Président de l'association Aguia JJB\n\nPropriété intellectuelle : L'ensemble du contenu de ce site (textes, images, logos) est la propriété exclusive de l'association Aguia JJB. Toute reproduction est interdite sans autorisation préalable.\n\nDonnées personnelles : Conformément au RGPD, vous disposez d'un droit d'accès, de rectification et de suppression des données vous concernant.\n\nCookies : Ce site n'utilise pas de cookies de suivi ou de publicité.\n\nResponsabilité : L'association ne pourra être tenue responsable des omissions ou inexactitudes.\n\nLiens hypertextes : L'association n'est pas responsable du contenu des sites externes.",
};

const DEFAULT_LOCATIONS = [
  { id: "1", name: "Cosec St Musse", city: "Toulon", address: "Cosec St Musse, Toulon", lat: 43.1242, lng: 5.9567, schedules: [{ day: "Mardi", time: "20h00 – 21h45" }, { day: "Mercredi", time: "18h30 – 20h00" }], color: C.redLight },
  { id: "2", name: "Complexe Sportif de l'Estagnol", city: "La Moutonne", address: "Vieux chemin d'Hyères, 83260 La Crau", lat: 43.1520, lng: 6.0730, schedules: [{ day: "Jeudi", time: "12h00 – 13h45" }, { day: "Vendredi", time: "12h00 – 13h45" }, { day: "Samedi", time: "14h00 – 16h00" }], color: C.gold },
  { id: "3", name: "La Serinette", city: "Toulon", address: "1377 chemin de la Barre, 83000 Toulon", lat: 43.1180, lng: 5.9350, schedules: [{ day: "Jeudi", time: "19h45 – 21h15" }], color: C.blueLight },
];

const DEFAULT_BLOG = [{ id: "1", title: "Bienvenue sur le nouveau site Aguia JJB !", date: "2025-09-01", excerpt: "Notre nouveau site est en ligne !", content: "Nous sommes ravis de vous présenter le nouveau site internet d'Aguia JJB.", image: "" }];
const DEFAULT_PALMARES = [{ id: "1", athlete: "—", competition: "—", result: "—", date: "—" }];
const DEFAULT_CONFIG = {
  bannerImage: BANNER_SRC,
  helloassoUrl: "https://www.helloasso.com/associations/aguia-jjb/adhesions/adhesion-2025-2026",
  socials: [
    { id: "fb", name: "Facebook", url: "https://www.facebook.com/AguiaJJB", type: "facebook" },
    { id: "ig", name: "Instagram", url: "https://www.instagram.com/aguiajjb", type: "instagram" },
  ],
};

// ─── ICONS ───────────────────────────────────
const Ic = {
  pin: (c="currentColor")=><svg width="18" height="18" fill="none" stroke={c} strokeWidth="2" viewBox="0 0 24 24"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 1118 0z"/><circle cx="12" cy="10" r="3"/></svg>,
  clock: ()=><svg width="15" height="15" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>,
  lock: ()=><svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0110 0v4"/></svg>,
  ext: ()=><svg width="13" height="13" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6M15 3h6v6M10 14L21 3"/></svg>,
  chev:(d="r")=><svg width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" style={{transform:d==="l"?"rotate(180deg)":""}}><path d="M9 18l6-6-6-6"/></svg>,
  plus: ()=><svg width="15" height="15" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>,
  trash: ()=><svg width="15" height="15" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M3 6h18M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/></svg>,
  save: ()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2z"/><path d="M17 21v-8H7v8M7 3v5h8"/></svg>,
  up: ()=><svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24"><path d="M18 15l-6-6-6 6"/></svg>,
  upload: ()=><svg width="15" height="15" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M17 8l-5-5-5 5M12 3v12"/></svg>,
  spin: ()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" style={{animation:"spin 1s linear infinite"}}><path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83"/></svg>,
  fb: ()=><svg width="20" height="20" fill="currentColor" viewBox="0 0 24 24"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>,
  ig: ()=><svg width="20" height="20" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 100 12.324 6.162 6.162 0 000-12.324zM12 16a4 4 0 110-8 4 4 0 010 8zm6.406-11.845a1.44 1.44 0 100 2.881 1.44 1.44 0 000-2.881z"/></svg>,
  yt: ()=><svg width="20" height="20" fill="currentColor" viewBox="0 0 24 24"><path d="M23.498 6.186a3.016 3.016 0 00-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 00.502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 002.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 002.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>,
  tt: ()=><svg width="20" height="20" fill="currentColor" viewBox="0 0 24 24"><path d="M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 1.4-.54 2.79-1.35 3.94-1.31 1.92-3.58 3.17-5.91 3.21-1.43.08-2.86-.31-4.08-1.03-2.02-1.19-3.44-3.37-3.65-5.71-.02-.5-.03-1-.01-1.49.18-1.9 1.12-3.72 2.58-4.96 1.66-1.44 3.98-2.13 6.15-1.72.02 1.48-.04 2.96-.04 4.44-.99-.32-2.15-.23-3.02.37-.63.41-1.11 1.04-1.36 1.75-.21.51-.15 1.07-.14 1.61.24 1.64 1.82 3.02 3.5 2.87 1.12-.01 2.19-.66 2.77-1.61.19-.33.4-.67.41-1.06.1-1.79.06-3.57.07-5.36.01-4.03-.01-8.05.02-12.07z"/></svg>,
  link: ()=><svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71"/></svg>,
};
const socIcons={facebook:Ic.fb,instagram:Ic.ig,youtube:Ic.yt,tiktok:Ic.tt,other:Ic.link};

// ─── SHARED ──────────────────────────────────
const hd={fontFamily:"'Teko',sans-serif",fontWeight:600};
const bt=(bg,col,brd)=>({display:"inline-flex",alignItems:"center",gap:8,padding:"12px 28px",borderRadius:6,border:brd||"none",background:bg,color:col,cursor:"pointer",fontFamily:"'Barlow',sans-serif",fontWeight:600,fontSize:14,transition:"all .3s",letterSpacing:.5});
const cd={background:C.card,borderRadius:12,border:`1px solid ${C.border}`,padding:24,transition:"all .3s"};
const ip={width:"100%",padding:"11px 14px",borderRadius:6,border:`1px solid ${C.border}`,background:C.bg,color:C.text,fontFamily:"'Barlow',sans-serif",fontSize:14,outline:"none"};
const lb={display:"block",fontSize:11,fontWeight:700,color:C.textMuted,marginBottom:5,textTransform:"uppercase",letterSpacing:1.5};
const tg=(color,text)=>(<div style={{display:"flex",alignItems:"center",gap:10,marginBottom:6}}><div style={{width:36,height:3,background:color,borderRadius:2}}/><span style={{fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:3,color}}>{text}</span></div>);

function ScrollTop(){const[s,sS]=useState(false);useEffect(()=>{const h=()=>sS(window.scrollY>400);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h)},[]);if(!s)return null;return<button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} style={{position:"fixed",bottom:24,right:24,zIndex:900,width:46,height:46,borderRadius:"50%",border:`1px solid ${C.border}`,background:`${C.card}ee`,backdropFilter:"blur(8px)",color:C.text,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",transition:"all .3s"}} onMouseEnter={e=>{e.currentTarget.style.background=C.redLight;e.currentTarget.style.borderColor=C.redLight}} onMouseLeave={e=>{e.currentTarget.style.background=`${C.card}ee`;e.currentTarget.style.borderColor=C.border}}>{Ic.up()}</button>}

function MapEmbed({locations,height=350}){const lats=locations.map(l=>l.lat),lngs=locations.map(l=>l.lng);const cLat=(Math.min(...lats)+Math.max(...lats))/2;const cLng=(Math.min(...lngs)+Math.max(...lngs))/2;const markersJs=locations.map(l=>`L.marker([${l.lat},${l.lng}]).addTo(map).bindPopup('<b>${l.name.replace(/'/g,"\\'")}</b><br>${l.city.replace(/'/g,"\\'")}');`).join("\n");const html=`<!DOCTYPE html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"><\/script><style>*{margin:0;padding:0}#map{width:100%;height:100vh}</style></head><body><div id="map"></div><script>var map=L.map('map',{scrollWheelZoom:false}).setView([${cLat},${cLng}],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);${markersJs}<\/script></body></html>`;return<div style={{borderRadius:12,overflow:"hidden",border:`1px solid ${C.border}`,width:"100%"}}><iframe title="Carte" width="100%" height={height} frameBorder="0" style={{border:0,display:"block"}} srcDoc={html} loading="lazy"/></div>}

function LocCard({loc,compact}){const[h,sH]=useState(false);return<div style={{...cd,borderLeft:`3px solid ${loc.color}`,transform:h?"translateY(-3px)":"",boxShadow:h?`0 8px 24px ${loc.color}22`:""}} onMouseEnter={()=>sH(true)} onMouseLeave={()=>sH(false)}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><div style={{color:loc.color}}>{Ic.pin(loc.color)}</div><div><div style={{...hd,fontSize:20,letterSpacing:1}}>{loc.name}</div><div style={{fontSize:12,color:C.textMuted}}>{loc.city}</div></div></div>{!compact&&<div style={{fontSize:13,color:C.textMuted,marginBottom:12}}>{loc.address}</div>}<div style={{display:"flex",flexDirection:"column",gap:6}}>{loc.schedules.map((sc,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8,fontSize:13}}>{Ic.clock()}<span style={{fontWeight:600,minWidth:75}}>{sc.day}</span><span style={{color:C.textMuted}}>{sc.time}</span></div>)}</div></div>}

function BlogCard({post,onClick}){const[h,sH]=useState(false);return<div style={{...cd,cursor:"pointer",transform:h?"translateY(-3px)":"",borderColor:h?C.blueLight:C.border,overflow:"hidden",padding:0}} onClick={onClick} onMouseEnter={()=>sH(true)} onMouseLeave={()=>sH(false)}>{post.image&&<div style={{width:"100%",height:160,overflow:"hidden"}}><img src={post.image} alt="" style={{width:"100%",height:"100%",objectFit:"cover",transition:"transform .4s",transform:h?"scale(1.05)":""}}/></div>}<div style={{padding:22}}><div style={{display:"inline-block",padding:"3px 10px",borderRadius:4,fontSize:11,fontWeight:700,background:`${C.blueLight}22`,color:C.blueLight,marginBottom:12,letterSpacing:1}}>{post.date}</div><h3 style={{...hd,fontSize:21,letterSpacing:.5,marginBottom:8}}>{post.title}</h3><p style={{fontSize:13,color:C.textMuted,lineHeight:1.6}}>{post.excerpt}</p><div style={{marginTop:14,color:C.blueLight,fontSize:12,fontWeight:600,display:"flex",alignItems:"center",gap:4}}>Lire la suite {Ic.chev()}</div></div></div>}

function SocialLinks({socials}){return<div style={{display:"flex",gap:14}}>{socials.map(s=>{const I=socIcons[s.type]||socIcons.other;return<a key={s.id} href={s.url} target="_blank" rel="noopener noreferrer" style={{color:C.textMuted,transition:"color .3s,transform .3s",display:"flex"}} onMouseEnter={e=>{e.currentTarget.style.color=C.redLight;e.currentTarget.style.transform="scale(1.15)"}} onMouseLeave={e=>{e.currentTarget.style.color=C.textMuted;e.currentTarget.style.transform=""}}>{I()}</a>})}</div>}

function Navbar({page,setPage}){const[sc,sSc]=useState(false);const[mob,sMob]=useState(false);useEffect(()=>{const h=()=>sSc(window.scrollY>40);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h)},[]);const links=[{id:"accueil",l:"Accueil"},{id:"offres",l:"Offres"},{id:"lieux",l:"Lieux & Horaires"},{id:"blog",l:"Blog"},{id:"palmares",l:"Palmarès"}];const go=p=>{setPage(p);sMob(false);window.scrollTo(0,0)};return<nav style={{position:"fixed",top:0,left:0,right:0,zIndex:1000,background:sc?`${C.bg}ee`:`${C.bg}88`,backdropFilter:"blur(14px)",borderBottom:`1px solid ${sc?C.border:"transparent"}`,transition:"all .4s"}}><div style={{maxWidth:1140,margin:"0 auto",padding:"0 20px",display:"flex",alignItems:"center",justifyContent:"space-between",height:68}}><div style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}} onClick={()=>go("accueil")}><img src={LOGO_SRC} alt="Aguia" style={{width:40,height:40,borderRadius:"50%"}}/><span style={{...hd,fontSize:22,letterSpacing:4}}>AGUIA JJB</span></div><div style={{display:"flex",gap:2,alignItems:"center"}} className="hm">{links.map(l=><button key={l.id} onClick={()=>go(l.id)} style={{background:page===l.id?`${C.redLight}20`:"transparent",color:page===l.id?C.redLight:C.textMuted,border:"none",padding:"7px 14px",borderRadius:5,cursor:"pointer",fontFamily:"'Barlow',sans-serif",fontSize:13,fontWeight:500,transition:"all .3s"}} onMouseEnter={e=>{if(page!==l.id)e.target.style.color=C.text}} onMouseLeave={e=>{if(page!==l.id)e.target.style.color=C.textMuted}}>{l.l}</button>)}</div><button onClick={()=>sMob(!mob)} className="sm" style={{display:"none",background:"none",border:"none",color:C.text,cursor:"pointer",padding:6}}><svg width="22" height="22" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">{mob?<path d="M18 6L6 18M6 6l12 12"/>:<path d="M3 12h18M3 6h18M3 18h18"/>}</svg></button></div>{mob&&<div style={{background:`${C.bg}f8`,backdropFilter:"blur(20px)",padding:"12px 20px",borderTop:`1px solid ${C.border}`}}>{links.map(l=><button key={l.id} onClick={()=>go(l.id)} style={{display:"block",width:"100%",textAlign:"left",background:page===l.id?`${C.redLight}18`:"transparent",color:page===l.id?C.redLight:C.text,border:"none",padding:"12px 14px",borderRadius:6,cursor:"pointer",fontFamily:"'Barlow',sans-serif",fontSize:15,fontWeight:500}}>{l.l}</button>)}</div>}</nav>}

function Footer({setPage,socials}){return<footer style={{borderTop:`1px solid ${C.border}`,padding:"36px 20px",marginTop:20}}><div style={{maxWidth:1100,margin:"0 auto",display:"flex",flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",gap:16}}><div style={{display:"flex",alignItems:"center",gap:10}}><img src={LOGO_SRC} alt="" style={{width:32,height:32,borderRadius:"50%"}}/><span style={{...hd,fontSize:18,letterSpacing:3}}>AGUIA JJB</span></div><SocialLinks socials={socials}/><div style={{display:"flex",gap:16,alignItems:"center",fontSize:11,color:C.textMuted}}><span style={{cursor:"pointer",transition:"color .3s"}} onMouseEnter={e=>e.target.style.color=C.text} onMouseLeave={e=>e.target.style.color=C.textMuted} onClick={()=>{setPage("legal");window.scrollTo(0,0)}}>Mentions légales</span><span>© 2025 Aguia JJB</span></div></div></footer>}

function compressImg(file){return new Promise((resolve)=>{const img=new Image();img.onload=()=>{const canvas=document.createElement("canvas");const MAX=600;let w=img.width,h=img.height;if(w>MAX){h=h*(MAX/w);w=MAX}canvas.width=w;canvas.height=h;canvas.getContext("2d").drawImage(img,0,0,w,h);resolve(canvas.toDataURL("image/jpeg",0.6))};img.src=URL.createObjectURL(file)})}
function ImgField({value,onChange,labelText}){const ref=useRef(null);const[upl,setUpl]=useState(false);const handleFile=async e=>{const f=e.target.files?.[0];if(!f)return;setUpl(true);try{const compressed=await compressImg(f);onChange(compressed)}catch{alert("Erreur lors de la compression")}setUpl(false);e.target.value=""};return<div><label style={lb}>{labelText}</label><div style={{display:"flex",gap:8,marginBottom:8}}><input value={typeof value==="string"&&value.startsWith("data:")?"(image uploadée)":value||""} placeholder="URL ou uploader" onChange={e=>onChange(e.target.value)} style={{...ip,flex:1}} readOnly={typeof value==="string"&&value.startsWith("data:")}/><button onClick={()=>ref.current?.click()} disabled={upl} style={{...bt(C.blueMid,"#fff"),padding:"8px 16px",fontSize:12,opacity:upl?.6:1}}>{upl?Ic.spin():Ic.upload()} {upl?"...":"Uploader"}</button><input ref={ref} type="file" accept="image/*" onChange={handleFile} style={{display:"none"}}/></div>{value&&<div style={{position:"relative",display:"inline-block"}}><img src={value} alt="" style={{maxHeight:80,borderRadius:6,objectFit:"cover",border:`1px solid ${C.border}`}} onError={e=>e.target.style.display="none"}/><button onClick={()=>onChange("")} style={{position:"absolute",top:-6,right:-6,width:20,height:20,borderRadius:"50%",background:C.redLight,border:"none",color:"#fff",cursor:"pointer",fontSize:10,display:"flex",alignItems:"center",justifyContent:"center"}}>✕</button></div>}</div>}

// ═══════════════════════════════════════════════
// PAGES
// ═══════════════════════════════════════════════
function LandingPage({texts:t,locations:locs,blog,config:cfg,setPage:go}){return<div style={{minHeight:"100vh"}}><section style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",textAlign:"center",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",inset:0,backgroundImage:`url(${cfg.bannerImage})`,backgroundSize:"cover",backgroundPosition:"center",filter:"brightness(0.25) contrast(1.1)"}}/><div style={{position:"absolute",inset:0,background:`linear-gradient(180deg,${C.bg}44 0%,${C.bg}bb 60%,${C.bg} 100%)`}}/><div style={{position:"absolute",inset:0,background:`radial-gradient(ellipse 70% 50% at 50% 30%,${C.red}18,transparent 70%)`}}/><div style={{position:"relative",zIndex:1,padding:"0 24px"}} className="an1"><img src={LOGO_SRC} alt="" style={{width:130,height:130,borderRadius:"50%",marginBottom:28,boxShadow:`0 0 50px ${C.red}40`}}/><h1 style={{...hd,fontSize:"clamp(3.5rem,10vw,7.5rem)",letterSpacing:10,lineHeight:.95,marginBottom:12}}>{t.heroTitle}</h1><p style={{fontSize:"clamp(.95rem,2.2vw,1.2rem)",color:C.textMuted,fontWeight:300,letterSpacing:3,marginBottom:44}}>{t.heroSubtitle}</p><div style={{display:"flex",gap:14,justifyContent:"center",flexWrap:"wrap"}}><button onClick={()=>{go("offres");window.scrollTo(0,0)}} style={{...bt(C.redLight,"#fff"),padding:"14px 36px",fontSize:15}} onMouseEnter={e=>{e.target.style.background=C.red;e.target.style.transform="scale(1.05)"}} onMouseLeave={e=>{e.target.style.background=C.redLight;e.target.style.transform=""}}>Rejoindre le club</button><button onClick={()=>{go("lieux");window.scrollTo(0,0)}} style={{...bt("transparent",C.text,`1px solid ${C.borderLight}`),padding:"14px 36px",fontSize:15}} onMouseEnter={e=>{e.target.style.borderColor=C.gold;e.target.style.color=C.gold}} onMouseLeave={e=>{e.target.style.borderColor=C.borderLight;e.target.style.color=C.text}}>Voir les horaires</button></div><div style={{marginTop:28}}><SocialLinks socials={cfg.socials}/></div></div><div style={{position:"absolute",bottom:28,animation:"pulse 2s infinite"}}><svg width="22" height="22" fill="none" stroke={C.textMuted} strokeWidth="2" viewBox="0 0 24 24"><path d="M7 13l5 5 5-5M7 6l5 5 5-5"/></svg></div></section>
<section style={{maxWidth:1100,margin:"0 auto",padding:"70px 24px"}}><div className="an1">{tg(C.redLight,"À propos")}<h2 style={{...hd,fontSize:"clamp(2rem,5vw,3rem)",letterSpacing:2,marginBottom:16}}>{t.aboutTitle}</h2><p style={{color:C.textMuted,lineHeight:1.8,fontSize:15,maxWidth:780,marginBottom:40}}>{t.aboutText}</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:16}} className="an2">{[{icon:"🥋",t:"Discipline",d:"Rigueur et engagement",col:C.redLight},{icon:"🤝",t:"Respect",d:"Valeur fondamentale",col:C.blueLight},{icon:"🔥",t:"Dépassement",d:"Se surpasser toujours",col:C.gold},{icon:"👥",t:"Communauté",d:"Solidarité et partage",col:C.redLight}].map((v,i)=><div key={i} style={{...cd,textAlign:"center",borderTop:`2px solid ${v.col}`}}><div style={{fontSize:32,marginBottom:10}}>{v.icon}</div><div style={{...hd,fontSize:18,letterSpacing:1,marginBottom:4}}>{v.t}</div><div style={{fontSize:12,color:C.textMuted}}>{v.d}</div></div>)}</div></section>
<div style={{height:1,background:`linear-gradient(90deg,transparent,${C.border},transparent)`}}/>
<section style={{maxWidth:1100,margin:"0 auto",padding:"70px 24px"}}><div className="an1">{tg(C.gold,"Entraînements")}<h2 style={{...hd,fontSize:"clamp(2rem,5vw,3rem)",letterSpacing:2,marginBottom:28}}>Où s'entraîner</h2></div><div className="an2" style={{marginBottom:24}}><MapEmbed locations={locs}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:16}} className="an3">{locs.map(l=><LocCard key={l.id} loc={l} compact/>)}</div></section>
<div style={{height:1,background:`linear-gradient(90deg,transparent,${C.border},transparent)`}}/>
<section style={{maxWidth:1100,margin:"0 auto",padding:"70px 24px"}}><div className="an1">{tg(C.blueLight,"Actualités")}<h2 style={{...hd,fontSize:"clamp(2rem,5vw,3rem)",letterSpacing:2,marginBottom:24}}>Dernières nouvelles</h2></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:16}} className="an2">{blog.slice(0,3).map(p=><BlogCard key={p.id} post={p} onClick={()=>{go("blog");window.scrollTo(0,0)}}/>)}</div></section>
<div style={{height:1,background:`linear-gradient(90deg,transparent,${C.border},transparent)`}}/>
<section style={{maxWidth:1100,margin:"0 auto",padding:"70px 24px",textAlign:"center"}}><div className="an1" style={{...cd,padding:"48px 36px",borderColor:C.redLight,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",inset:0,background:`linear-gradient(135deg,${C.red}12,transparent 50%)`}}/><div style={{position:"relative"}}><h2 style={{...hd,fontSize:"clamp(2rem,5vw,2.8rem)",letterSpacing:2,marginBottom:10}}>{t.ctaTitle}</h2><p style={{color:C.textMuted,fontSize:15,marginBottom:28,maxWidth:460,margin:"0 auto 28px"}}>{t.ctaText}</p><a href={cfg.helloassoUrl} target="_blank" rel="noopener noreferrer" style={{...bt(C.redLight,"#fff"),textDecoration:"none",padding:"14px 36px"}} onMouseEnter={e=>e.target.style.transform="scale(1.05)"} onMouseLeave={e=>e.target.style.transform=""}>S'inscrire {Ic.ext()}</a></div></div></section>
<Footer setPage={go} socials={cfg.socials}/></div>}

function OffresPage({texts:t,config:cfg,setPage:go}){return<div style={{minHeight:"100vh",paddingTop:80}}><section style={{maxWidth:1100,margin:"0 auto",padding:"60px 24px"}}><div className="an1">{tg(C.redLight,"Inscription")}<h1 style={{...hd,fontSize:"clamp(2rem,5vw,3.2rem)",letterSpacing:2,marginBottom:8}}>{t.offresTitle}</h1><p style={{color:C.textMuted,lineHeight:1.8,fontSize:15,maxWidth:680,marginBottom:36}}>{t.offresIntro}</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:20,marginBottom:32}} className="an2"><div style={{...cd,borderTop:`3px solid ${C.gold}`}}><div style={{display:"inline-block",padding:"3px 10px",borderRadius:4,fontSize:11,fontWeight:700,background:`${C.gold}22`,color:C.gold,marginBottom:14,letterSpacing:1}}>GRATUIT</div><h3 style={{...hd,fontSize:26,letterSpacing:1,marginBottom:8}}>{t.offresEssaiTitle}</h3><p style={{color:C.textMuted,lineHeight:1.6,fontSize:14}}>{t.offresEssaiText}</p></div><div style={{...cd,borderTop:`3px solid ${C.redLight}`,position:"relative"}}><div style={{position:"absolute",top:12,right:12,background:C.redLight,color:"#fff",padding:"3px 12px",borderRadius:4,fontSize:10,fontWeight:700,letterSpacing:1}}>POPULAIRE</div><div style={{display:"inline-block",padding:"3px 10px",borderRadius:4,fontSize:11,fontWeight:700,background:`${C.redLight}22`,color:C.redLight,marginBottom:14,letterSpacing:1}}>SAISON 2025-2026</div><h3 style={{...hd,fontSize:26,letterSpacing:1,marginBottom:8}}>{t.offresAdhesionTitle}</h3><p style={{color:C.textMuted,lineHeight:1.6,fontSize:14,marginBottom:20}}>{t.offresAdhesionText}</p><a href={cfg.helloassoUrl} target="_blank" rel="noopener noreferrer" style={{...bt(C.redLight,"#fff"),textDecoration:"none",width:"100%",justifyContent:"center"}}>S'inscrire sur HelloAsso {Ic.ext()}</a></div></div><div className="an3" style={{...cd,borderLeft:`3px solid ${C.gold}`}}><div style={{display:"flex",gap:14}}><span style={{fontSize:24}}>⚠️</span><div><h3 style={{...hd,fontSize:20,color:C.gold,marginBottom:6}}>Important</h3><p style={{color:C.textMuted,lineHeight:1.7,fontSize:14}}>{t.offresImportant}</p></div></div></div></section><Footer setPage={go} socials={cfg.socials}/></div>}

function LieuxPage({texts:t,locations:locs,config:cfg,setPage:go}){return<div style={{minHeight:"100vh",paddingTop:80}}><section style={{maxWidth:1100,margin:"0 auto",padding:"60px 24px"}}><div className="an1">{tg(C.gold,"Planning")}<h1 style={{...hd,fontSize:"clamp(2rem,5vw,3.2rem)",letterSpacing:2,marginBottom:8}}>{t.lieuxTitle}</h1><p style={{color:C.textMuted,fontSize:14,marginBottom:28,maxWidth:550}}>{t.lieuxSubtitle}</p></div><div className="an2" style={{marginBottom:28}}><MapEmbed locations={locs} height={380}/></div><div style={{display:"grid",gap:20}}>{locs.map((loc,i)=><div key={loc.id} className={`an${Math.min(i+2,4)}`}><LocCard loc={loc}/></div>)}</div></section><Footer setPage={go} socials={cfg.socials}/></div>}

function BlogPage({texts:t,blog,config:cfg,setPage:go}){const[sel,setSel]=useState(null);if(sel){const post=blog.find(b=>b.id===sel);return<div style={{minHeight:"100vh",paddingTop:80}}><section style={{maxWidth:800,margin:"0 auto",padding:"60px 24px"}}><button onClick={()=>setSel(null)} style={{...bt("transparent",C.textMuted,`1px solid ${C.border}`),padding:"8px 16px",fontSize:13,marginBottom:24}}>{Ic.chev("l")} Retour</button><div className="an1"><div style={{display:"inline-block",padding:"3px 10px",borderRadius:4,fontSize:11,fontWeight:700,background:`${C.blueLight}22`,color:C.blueLight,marginBottom:14}}>{post.date}</div><h1 style={{...hd,fontSize:"clamp(2rem,5vw,3rem)",letterSpacing:1,marginBottom:20}}>{post.title}</h1>{post.image&&<img src={post.image} alt="" style={{width:"100%",borderRadius:10,marginBottom:24,maxHeight:400,objectFit:"cover"}}/>}<div style={{color:C.textMuted,lineHeight:1.9,fontSize:15,whiteSpace:"pre-line"}}>{post.content}</div></div></section><Footer setPage={go} socials={cfg.socials}/></div>}return<div style={{minHeight:"100vh",paddingTop:80}}><section style={{maxWidth:1100,margin:"0 auto",padding:"60px 24px"}}><div className="an1">{tg(C.blueLight,"Actualités")}<h1 style={{...hd,fontSize:"clamp(2rem,5vw,3.2rem)",letterSpacing:2,marginBottom:8}}>{t.blogTitle}</h1><p style={{color:C.textMuted,fontSize:14,marginBottom:28,maxWidth:550}}>{t.blogSubtitle}</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:16}}>{blog.map((p,i)=><div key={p.id} className={`an${Math.min(i+1,4)}`}><BlogCard post={p} onClick={()=>setSel(p.id)}/></div>)}</div>{blog.length===0&&<div style={{textAlign:"center",padding:60,color:C.textMuted}}>Aucun article.</div>}</section><Footer setPage={go} socials={cfg.socials}/></div>}

function PalmaresPage({texts:t,palmares,config:cfg,setPage:go}){return<div style={{minHeight:"100vh",paddingTop:80}}><section style={{maxWidth:1100,margin:"0 auto",padding:"60px 24px"}}><div className="an1">{tg(C.gold,"Résultats")}<h1 style={{...hd,fontSize:"clamp(2rem,5vw,3.2rem)",letterSpacing:2,marginBottom:8}}>{t.palmaresTitle}</h1><p style={{color:C.textMuted,fontSize:14,marginBottom:28,maxWidth:550}}>{t.palmaresIntro}</p></div><div className="an2" style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"separate",borderSpacing:"0 6px"}}><thead><tr>{["Athlète","Compétition","Résultat","Date"].map(h=><th key={h} style={{textAlign:"left",padding:"10px 14px",fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:2,color:C.textMuted,borderBottom:`1px solid ${C.border}`}}>{h}</th>)}</tr></thead><tbody>{palmares.map(r=><tr key={r.id} style={{background:C.card}}><td style={{padding:"12px 14px",borderRadius:"6px 0 0 6px",fontWeight:600}}>{r.athlete}</td><td style={{padding:"12px 14px"}}>{r.competition}</td><td style={{padding:"12px 14px"}}><span style={{display:"inline-block",padding:"3px 10px",borderRadius:4,fontSize:11,fontWeight:700,background:`${C.gold}22`,color:C.gold}}>{r.result}</span></td><td style={{padding:"12px 14px",borderRadius:"0 6px 6px 0",color:C.textMuted}}>{r.date}</td></tr>)}</tbody></table></div></section><Footer setPage={go} socials={cfg.socials}/></div>}

function LegalPage({texts:t,config:cfg,setPage:go}){return<div style={{minHeight:"100vh",paddingTop:80}}><section style={{maxWidth:800,margin:"0 auto",padding:"60px 24px"}}><div className="an1">{tg(C.textMuted,"Juridique")}<h1 style={{...hd,fontSize:"clamp(2rem,5vw,3.2rem)",letterSpacing:2,marginBottom:24}}>{t.legalTitle}</h1><div style={{...cd,padding:32}}><div style={{color:C.textMuted,lineHeight:1.9,fontSize:14,whiteSpace:"pre-line"}}>{t.legalContent}</div></div></div></section><Footer setPage={go} socials={cfg.socials}/></div>}

// ═══════════════════════════════════════════════
// ADMIN
// ═══════════════════════════════════════════════
function AdminPage({texts,setTexts,locations,setLocations,blog,setBlog,palmares,setPalmares,config,setConfig,saveAll}){
  const[auth,setAuth]=useState(false);const[code,setCode]=useState("");const[err,setErr]=useState("");const[tab,setTab]=useState("texts");
  if(!auth)return<div style={{minHeight:"100vh",paddingTop:80}}><section style={{maxWidth:400,margin:"0 auto",padding:"80px 24px",textAlign:"center"}}><div className="an1" style={{...cd,padding:36}}><div style={{margin:"0 auto 18px",width:56,height:56,borderRadius:"50%",background:`${C.red}20`,display:"flex",alignItems:"center",justifyContent:"center",color:C.redLight}}>{Ic.lock()}</div><h2 style={{...hd,fontSize:28,letterSpacing:2,marginBottom:6}}>Panneau Admin</h2><p style={{color:C.textMuted,fontSize:13,marginBottom:22}}>Entrez le code administrateur.</p><input type="password" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(code===ADMIN_CODE?setAuth(true):setErr("Code incorrect"))} placeholder="Code admin" style={{...ip,textAlign:"center",marginBottom:14}}/>{err&&<p style={{color:C.redLight,fontSize:12,marginBottom:10}}>{err}</p>}<button onClick={()=>code===ADMIN_CODE?setAuth(true):setErr("Code incorrect")} style={{...bt(C.redLight,"#fff"),width:"100%",justifyContent:"center"}}>Connexion</button></div></section></div>;

  const tabs=[{id:"texts",l:"📝 Textes"},{id:"locations",l:"📍 Lieux"},{id:"blog",l:"📰 Blog"},{id:"palmares",l:"🏆 Palmarès"},{id:"config",l:"⚙️ Config"}];
  const tGrp=[{title:"Page Accueil",keys:["heroTitle","heroSubtitle","aboutTitle","aboutText","ctaTitle","ctaText"]},{title:"Page Offres",keys:["offresTitle","offresIntro","offresEssaiTitle","offresEssaiText","offresAdhesionTitle","offresAdhesionText","offresImportant"]},{title:"Page Lieux",keys:["lieuxTitle","lieuxSubtitle"]},{title:"Page Blog",keys:["blogTitle","blogSubtitle"]},{title:"Page Palmarès",keys:["palmaresTitle","palmaresIntro"]},{title:"Mentions Légales",keys:["legalTitle","legalContent"]}];
  const lMap={heroTitle:"Titre Hero",heroSubtitle:"Sous-titre",aboutTitle:"Titre À propos",aboutText:"Texte À propos",ctaTitle:"Titre CTA",ctaText:"Texte CTA",offresTitle:"Titre",offresIntro:"Introduction",offresEssaiTitle:"Titre Essai",offresEssaiText:"Texte Essai",offresAdhesionTitle:"Titre Adhésion",offresAdhesionText:"Texte Adhésion",offresImportant:"Note importante",lieuxTitle:"Titre",lieuxSubtitle:"Sous-titre",blogTitle:"Titre",blogSubtitle:"Sous-titre",palmaresTitle:"Titre",palmaresIntro:"Introduction",legalTitle:"Titre",legalContent:"Contenu"};
  const socTypes=[{v:"facebook",l:"Facebook"},{v:"instagram",l:"Instagram"},{v:"youtube",l:"YouTube"},{v:"tiktok",l:"TikTok"},{v:"other",l:"Autre"}];

  return<div style={{minHeight:"100vh",paddingTop:80}}><section style={{maxWidth:1100,margin:"0 auto",padding:"40px 24px"}}>
    <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:14,marginBottom:28}}><div><h1 style={{...hd,fontSize:30,letterSpacing:2}}>Panneau Admin</h1><p style={{color:C.textMuted,fontSize:13}}>Sauvegardé dans Firebase</p></div><button onClick={saveAll} style={{...bt(C.redLight,"#fff")}}>{Ic.save()} Sauvegarder</button></div>
    <div style={{display:"flex",gap:4,marginBottom:28,overflowX:"auto",paddingBottom:4}}>{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} style={{...bt(tab===t.id?C.redLight:"transparent",tab===t.id?"#fff":C.textMuted,tab===t.id?"":"1px solid "+C.border),padding:"8px 18px",fontSize:13,whiteSpace:"nowrap"}}>{t.l}</button>)}</div>

    {tab==="texts"&&<div style={{display:"grid",gap:24}}>{tGrp.map(g=><div key={g.title} style={cd}><h3 style={{...hd,fontSize:20,color:C.gold,marginBottom:18,letterSpacing:1}}>{g.title}</h3><div style={{display:"grid",gap:14}}>{g.keys.map(k=><div key={k}><label style={lb}>{lMap[k]||k}</label>{(texts[k]||"").length>80?<textarea value={texts[k]} onChange={e=>setTexts(p=>({...p,[k]:e.target.value}))} style={{...ip,minHeight:100,resize:"vertical"}}/>:<input value={texts[k]} onChange={e=>setTexts(p=>({...p,[k]:e.target.value}))} style={ip}/>}</div>)}</div></div>)}</div>}

    {tab==="locations"&&<div style={{display:"grid",gap:20}}>{locations.map((loc,li)=><div key={loc.id} style={cd}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><h3 style={{...hd,fontSize:20}}>Lieu {li+1}</h3><button onClick={()=>setLocations(p=>p.filter(l=>l.id!==loc.id))} style={{...bt(`${C.red}15`,C.redLight),padding:"6px 14px",fontSize:12,border:"none"}}>{Ic.trash()} Suppr.</button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:12}}><div><label style={lb}>Nom</label><input value={loc.name} onChange={e=>setLocations(p=>p.map(l=>l.id===loc.id?{...l,name:e.target.value}:l))} style={ip}/></div><div><label style={lb}>Ville</label><input value={loc.city} onChange={e=>setLocations(p=>p.map(l=>l.id===loc.id?{...l,city:e.target.value}:l))} style={ip}/></div></div><div style={{marginBottom:12}}><label style={lb}>Adresse</label><input value={loc.address} onChange={e=>setLocations(p=>p.map(l=>l.id===loc.id?{...l,address:e.target.value}:l))} style={ip}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:14}}><div><label style={lb}>Latitude</label><input type="number" step="0.0001" value={loc.lat} onChange={e=>setLocations(p=>p.map(l=>l.id===loc.id?{...l,lat:parseFloat(e.target.value)||0}:l))} style={ip}/></div><div><label style={lb}>Longitude</label><input type="number" step="0.0001" value={loc.lng} onChange={e=>setLocations(p=>p.map(l=>l.id===loc.id?{...l,lng:parseFloat(e.target.value)||0}:l))} style={ip}/></div></div><label style={lb}>Horaires</label>{loc.schedules.map((sc,si)=><div key={si} style={{display:"flex",gap:8,marginBottom:6,alignItems:"center"}}><input value={sc.day} placeholder="Jour" onChange={e=>{const ns=[...loc.schedules];ns[si]={...ns[si],day:e.target.value};setLocations(p=>p.map(l=>l.id===loc.id?{...l,schedules:ns}:l))}} style={{...ip,flex:1}}/><input value={sc.time} placeholder="Horaire" onChange={e=>{const ns=[...loc.schedules];ns[si]={...ns[si],time:e.target.value};setLocations(p=>p.map(l=>l.id===loc.id?{...l,schedules:ns}:l))}} style={{...ip,flex:1}}/><button onClick={()=>{const ns=loc.schedules.filter((_,i)=>i!==si);setLocations(p=>p.map(l=>l.id===loc.id?{...l,schedules:ns}:l))}} style={{background:"none",border:"none",color:C.redLight,cursor:"pointer",padding:4}}>{Ic.trash()}</button></div>)}<button onClick={()=>{const ns=[...loc.schedules,{day:"",time:""}];setLocations(p=>p.map(l=>l.id===loc.id?{...l,schedules:ns}:l))}} style={{...bt("transparent",C.textMuted,`1px solid ${C.border}`),padding:"6px 14px",fontSize:12,marginTop:4}}>{Ic.plus()} Horaire</button></div>)}<button onClick={()=>setLocations(p=>[...p,{id:Date.now().toString(),name:"",city:"",address:"",lat:43.12,lng:5.94,schedules:[{day:"",time:""}],color:C.blueLight}])} style={{...bt("transparent",C.text,`1px solid ${C.border}`),justifyContent:"center"}}>{Ic.plus()} Ajouter un lieu</button></div>}

    {tab==="blog"&&<div style={{display:"grid",gap:20}}>{blog.map((post,pi)=><div key={post.id} style={cd}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><h3 style={{...hd,fontSize:20}}>Article {pi+1}</h3><button onClick={()=>setBlog(p=>p.filter(b=>b.id!==post.id))} style={{...bt(`${C.red}15`,C.redLight),padding:"6px 14px",fontSize:12,border:"none"}}>{Ic.trash()} Suppr.</button></div><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:10,marginBottom:10}}><div><label style={lb}>Titre</label><input value={post.title} onChange={e=>setBlog(p=>p.map(b=>b.id===post.id?{...b,title:e.target.value}:b))} style={ip}/></div><div><label style={lb}>Date</label><input type="date" value={post.date} onChange={e=>setBlog(p=>p.map(b=>b.id===post.id?{...b,date:e.target.value}:b))} style={ip}/></div></div><div style={{marginBottom:10}}><ImgField value={post.image} labelText="Image" onChange={v=>setBlog(p=>p.map(b=>b.id===post.id?{...b,image:v}:b))}/></div><div style={{marginBottom:10}}><label style={lb}>Extrait</label><input value={post.excerpt} onChange={e=>setBlog(p=>p.map(b=>b.id===post.id?{...b,excerpt:e.target.value}:b))} style={ip}/></div><div><label style={lb}>Contenu</label><textarea value={post.content} onChange={e=>setBlog(p=>p.map(b=>b.id===post.id?{...b,content:e.target.value}:b))} style={{...ip,minHeight:100,resize:"vertical"}}/></div></div>)}<button onClick={()=>setBlog(p=>[...p,{id:Date.now().toString(),title:"",date:new Date().toISOString().split("T")[0],excerpt:"",content:"",image:""}])} style={{...bt("transparent",C.text,`1px solid ${C.border}`),justifyContent:"center"}}>{Ic.plus()} Nouvel article</button></div>}

    {tab==="palmares"&&<div style={{display:"grid",gap:10}}>{palmares.map(row=><div key={row.id} style={{...cd,display:"flex",gap:10,alignItems:"end",flexWrap:"wrap"}}><div style={{flex:"1 1 140px"}}><label style={lb}>Athlète</label><input value={row.athlete} onChange={e=>setPalmares(p=>p.map(r=>r.id===row.id?{...r,athlete:e.target.value}:r))} style={ip}/></div><div style={{flex:"1 1 140px"}}><label style={lb}>Compétition</label><input value={row.competition} onChange={e=>setPalmares(p=>p.map(r=>r.id===row.id?{...r,competition:e.target.value}:r))} style={ip}/></div><div style={{flex:"1 1 100px"}}><label style={lb}>Résultat</label><input value={row.result} onChange={e=>setPalmares(p=>p.map(r=>r.id===row.id?{...r,result:e.target.value}:r))} style={ip}/></div><div style={{flex:"0 0 110px"}}><label style={lb}>Date</label><input value={row.date} onChange={e=>setPalmares(p=>p.map(r=>r.id===row.id?{...r,date:e.target.value}:r))} style={ip}/></div><button onClick={()=>setPalmares(p=>p.filter(r=>r.id!==row.id))} style={{background:"none",border:"none",color:C.redLight,cursor:"pointer",padding:"8px 4px"}}>{Ic.trash()}</button></div>)}<button onClick={()=>setPalmares(p=>[...p,{id:Date.now().toString(),athlete:"",competition:"",result:"",date:""}])} style={{...bt("transparent",C.text,`1px solid ${C.border}`),justifyContent:"center"}}>{Ic.plus()} Ajouter</button></div>}

    {tab==="config"&&<div style={{display:"grid",gap:24}}>
      <div style={cd}><h3 style={{...hd,fontSize:20,color:C.gold,marginBottom:18}}>Bannière</h3><ImgField value={config.bannerImage} labelText="Image bannière" onChange={v=>setConfig(p=>({...p,bannerImage:v}))}/></div>
      <div style={cd}><h3 style={{...hd,fontSize:20,color:C.gold,marginBottom:18}}>Lien HelloAsso</h3><label style={lb}>URL</label><input value={config.helloassoUrl} onChange={e=>setConfig(p=>({...p,helloassoUrl:e.target.value}))} style={ip}/></div>
      <div style={cd}><h3 style={{...hd,fontSize:20,color:C.gold,marginBottom:18}}>Réseaux Sociaux</h3>{config.socials.map((soc,si)=><div key={soc.id} style={{display:"flex",gap:8,marginBottom:10,alignItems:"end",flexWrap:"wrap"}}><div style={{flex:"0 0 130px"}}><label style={lb}>Type</label><select value={soc.type} onChange={e=>{const ns=[...config.socials];ns[si]={...ns[si],type:e.target.value};setConfig(p=>({...p,socials:ns}))}} style={{...ip,cursor:"pointer"}}>{socTypes.map(st=><option key={st.v} value={st.v}>{st.l}</option>)}</select></div><div style={{flex:"1 1 120px"}}><label style={lb}>Nom</label><input value={soc.name} onChange={e=>{const ns=[...config.socials];ns[si]={...ns[si],name:e.target.value};setConfig(p=>({...p,socials:ns}))}} style={ip}/></div><div style={{flex:"2 1 200px"}}><label style={lb}>URL</label><input value={soc.url} onChange={e=>{const ns=[...config.socials];ns[si]={...ns[si],url:e.target.value};setConfig(p=>({...p,socials:ns}))}} style={ip}/></div><button onClick={()=>setConfig(p=>({...p,socials:p.socials.filter((_,i)=>i!==si)}))} style={{background:"none",border:"none",color:C.redLight,cursor:"pointer",padding:"8px 4px"}}>{Ic.trash()}</button></div>)}<button onClick={()=>setConfig(p=>({...p,socials:[...p.socials,{id:Date.now().toString(),name:"",url:"",type:"other"}]}))} style={{...bt("transparent",C.textMuted,`1px solid ${C.border}`),padding:"6px 14px",fontSize:12,marginTop:4}}>{Ic.plus()} Ajouter</button></div>
    </div>}

    <div style={{marginTop:36,textAlign:"center"}}><button onClick={saveAll} style={{...bt(C.redLight,"#fff"),padding:"14px 54px"}}>{Ic.save()} Sauvegarder tout</button><p style={{color:C.textMuted,fontSize:11,marginTop:10}}>Visible par tous les visiteurs.</p></div>
  </section></div>;
}

// ═══════════════════════════════════════════════
// APP
// ═══════════════════════════════════════════════
export default function App(){
  const[page,setPage]=useState("accueil");
  
  const[texts,setTexts]=useState(DEFAULT_TEXTS);
  const[locations,setLocations]=useState(DEFAULT_LOCATIONS);
  const[blog,setBlog]=useState(DEFAULT_BLOG);
  const[palmares,setPalmares]=useState(DEFAULT_PALMARES);
  const[config,setConfig]=useState(DEFAULT_CONFIG);
  const[toast,setToast]=useState("");

  useEffect(()=>{const h=()=>{if(window.location.hash==="#admin")setPage("admin")};h();window.addEventListener("hashchange",h);return()=>window.removeEventListener("hashchange",h)},[]);

  useEffect(()=>{(async()=>{try{const d=await fbLoad();if(d){d.texts&&setTexts(p=>({...p,...d.texts}));d.locations&&setLocations(d.locations);d.blog&&setBlog(d.blog);d.palmares&&setPalmares(d.palmares);d.config&&setConfig(p=>({...p,...d.config}))}}catch(e){console.error(e)}})()},[]);

  const saveAll=useCallback(async()=>{try{await fbSave({texts,locations,blog,palmares,config});setToast("ok");setTimeout(()=>setToast(""),2500)}catch(e){console.error("SAVE FAILED:",e);setToast("err");setTimeout(()=>setToast(""),5000)}},[texts,locations,blog,palmares,config]);

  return<div style={{minHeight:"100vh",background:C.bg}}>
    <style>{`@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`}</style>
    <Navbar page={page} setPage={setPage}/>
    {page==="accueil"&&<LandingPage texts={texts} locations={locations} blog={blog} config={config} setPage={setPage}/>}
    {page==="offres"&&<OffresPage texts={texts} config={config} setPage={setPage}/>}
    {page==="lieux"&&<LieuxPage texts={texts} locations={locations} config={config} setPage={setPage}/>}
    {page==="blog"&&<BlogPage texts={texts} blog={blog} config={config} setPage={setPage}/>}
    {page==="palmares"&&<PalmaresPage texts={texts} palmares={palmares} config={config} setPage={setPage}/>}
    {page==="legal"&&<LegalPage texts={texts} config={config} setPage={setPage}/>}
    {page==="admin"&&<AdminPage texts={texts} setTexts={setTexts} locations={locations} setLocations={setLocations} blog={blog} setBlog={setBlog} palmares={palmares} setPalmares={setPalmares} config={config} setConfig={setConfig} saveAll={saveAll}/>}
    <ScrollTop/>
    {toast==="ok"&&<div style={{position:"fixed",bottom:80,right:24,background:"#166534",color:"#fff",padding:"12px 24px",borderRadius:8,fontWeight:600,fontSize:13,animation:"fadeUp .3s ease",fontFamily:"'Barlow',sans-serif",zIndex:9999}}>✓ Sauvegardé !</div>}
    {toast==="err"&&<div style={{position:"fixed",bottom:80,right:24,background:C.redLight,color:"#fff",padding:"12px 24px",borderRadius:8,fontWeight:600,fontSize:13,animation:"fadeUp .3s ease",fontFamily:"'Barlow',sans-serif",zIndex:9999,maxWidth:350}}>✕ Erreur de sauvegarde — vérifiez la console (F12)</div>}
  </div>;
}
